# OneScript GitHub Linguist Official Registration Definition
# Repository: github-linguist/linguist

OneScript:
  type: markup
  color: "#6366f1"
  aliases:
  - one
  - onescript
  extensions:
  - ".one"
  tm_scope: text.html.onescript
  ace_mode: html
  codemirror_mode: htmlmixed
  codemirror_mime_type: text/html
  language_id: 89347592
